constants:
  file:
    directory: /home/download
  jwt:
    refresh-token-cookie-path: /mujiuniv-api/api/auth/reissue

eureka:
  client:
    enabled: false

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
        strategy: refresh
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.0.39/final_project_user
  jpa:
    hibernate:
      ddl-auto: update
    lifecycle:
      timeout-per-shutdown-phase: 30s  # Pod 종료 대기 시간